---
micronaut:
  application:
    name: library-service

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/library-service"
  cluster:
    maxWaitQueueSize: 5
  connectionPool:
    maxSize: 20
